export enum ActionTypeStudent {
    CREATE_STUDENT = "CREATE_STUDENT",
    EDIT_STUDENT = "EDIT_STUDENT",
    DELETE_STUDENT = "DELETE_STUDENT",
    GETALL_STUDENTS = "GETALL_STUDENTS",
    STUDENTS_ERROR = "STUDENTS_ERROR",
  }
